import { HeroUIProvider } from "@heroui/react";
import ScriptLoader from "@/app/components/ScriptLoader";
import { ThemeProvider } from "@/app/context/ThemeContext";
import Header from "@/app/components/HeaderComponent";
import { BaleProvider } from "@/app/context/BaleContext";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      // dir="rtl"
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ScriptLoader />
        <ThemeProvider>
          <HeroUIProvider>
            <BaleProvider>
              {/* <Header /> */}
              {children}
            </BaleProvider>
          </HeroUIProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
