import ScriptLoader from "@/app/components/ScriptLoader";
// import ThemeProvider from "@/app/components/ThemeProvider";
import { ThemeProvider } from "@/app/components/ThemeContext";
import Header from "@/app/components/HeaderComponent";
import CloseHandler from "@/app/components/CloseHandler";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ScriptLoader />
        <CloseHandler />
        <ThemeProvider>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
